### ISSUE TITLE
Plugin locks up when I add DSD codec to Sony BR player

### ISSUE THREAD

**Issue by Warpshock** [philippe44/LMS-uPnP#58]
I am trying to get native DSD playback of DSD.

My player is a Sony UBP-X700 player. It reports DSD, DSF, DFF support over DLNA. However, when I add any of these codecs, the UPnP plugin will crash and will not reload again unless I delete all config files and reinstall. I have confirmed shutdown of the exe before config changes. Even when I manually delete the codec section from the XML file, the plugin still won't load unless uninstalled and the config files are deleted.

As a comparison, TwonkyMedia server works with my player and plays DSD files natively. It reports DSD support over DLNA

**Comment by philippe44** [comment]
I'm not a user of DSD? can you please ask on the LMS forum?
