### ISSUE TITLE
Playing native DSD (DSF file)

### ISSUE THREAD

**Issue by PhilB-RLB** [philippe44/LMS-uPnP#61]
Hello,

I use Squeeze2upnp plugin from Daphile.
No problem to read HD flac with my upnp receiver (Cabasse Pearl).

Now I would like to know how to configure the squeeze2upnp plugin in order to send dsf file which can be directly decoded with Cabasse Pearl.

Any advice on this ?

**Comment by philippe44** [comment]
I'm not a user of DSD, so I don't know but maybe other folks on the forum would
