### ISSUE TITLE
latest release from 8/12/22 - v2.1.1 - not discovering devices

### ISSUE THREAD

**Issue by mamema** [philippe44/LMS-uPnP#65]
Hi Philippe,

i'm using this plugin several years, have several UPNP devices which after update to the release in question, no longer discover my devices.

Log:
Starting Squeeze2upnp: /config/cache/InstalledPlugins/Plugins/UPnPBridge/Bin/squeeze2upnp-linux-x86_64-static -Z -I -f /config/logs/upnpbridge.log -d all=debug -x /config/prefs/upnpbridge.xml
[16:54:08.740597] main:1725 Starting squeeze2upnp version: v2.1.1 (Dec  8 2022 @ 16:45:23)
[16:54:08.794826] register_alac:541 using alac to decode alc
[16:54:08.794872] register_mad:433 using mad to decode mp3
[16:54:08.794882] register_faad:647 using faad to decode aac
[16:54:08.794896] register_vorbis:346 using vorbis to decode ogg
[16:54:08.794904] register_pcm:339 using pcm
[16:54:08.794938] register_flac:313 using flac to decode flc
[16:54:08.794947] register_opus:286 using opus to decode ops
[16:54:08.794957] register_m4a_thru:308 using mp4 to aac (ADTS)
[16:54:08.794967] register_flac_thru:213 using flac
[16:54:08.794978] register_thru:107 using thru
[16:54:08.794988] register_soxr:391 using soxr for resampling
[16:54:08.795005] Start:1488 Binding to 192.168.0.x:49152 (http:0)
[16:54:28.003131] UpdateThread:1095 Presence checking

nothing more in the logs.
regenerating the xml isn't solving the discover problem.

**Comment by philippe44** [comment]
What is your network configuration (in term of multi interface)

**Comment by mamema** [comment]
i've tried several settings. The actual working setting was (in the LMS Interface area in your plugin): 192.168.0.x:, Netmask 255.255.255.0
i've tried ? and "use LMS interface"

see attached working  (before update)
____
<squeeze2upnp>
  <main_log>info</main_log>
  <log_limit>-1</log_limit>
  <output_log>info</output_log>
  <slimproto_log>info</slimproto_log>
  <upnp_log>info</upnp_log>
  <binding>192.168.0.30</binding>
  <common>
    <volume_on_play>1</volume_on_play>
    <codecs>aac,ogg,ops,ogf,flc,alc,wav,aif,pcm,mp3</codecs>
    <raw_audio_format>raw,wav,aif</raw_audio_format>
    <stream_length>-3</stream_length>
    <max_volume>100</max_volume>
    <sample_rate>48000</sample_rate>
    <send_icy>1</send_icy>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>1</send_coverart>
    <flac_header>1</flac_header>
    <seek_after_pause>0</seek_after_pause>
    <streambuf_size>1048576</streambuf_size>
    <roon_mode>0</roon_mode>
    <L24_format>1</L24_format>
    <send_metadata>1</send_metadata>
    <mode>thru</mode>
    <volume_feedback>1</volume_feedback>
    <enabled>1</enabled>
    <next_delay>15</next_delay>
    <auto_play>0</auto_play>
    <remove_timeout>120</remove_timeout>
    <server>?</server>
    <output_size>4194304</output_size>
  </common>
  <decode_log>warn</decode_log>
  <util_log>warn</util_log>
  <stream_log>warn</stream_log>
  <slimmain_log>warn</slimmain_log>
  <device>
    <friendly_name>Aries uPnP </friendly_name>
    <seek_after_pause>1</seek_after_pause>
    <flac_header>1</flac_header>
    <mac>bb:bb:f0:6f:8d:50</mac>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>0</send_coverart>
    <mode>thru</mode>
    <enabled>1</enabled>
    <udn>uuid:lightningRender-bc-34-00-a0-1b-2f</udn>
    <send_metadata>0</send_metadata>
    <L24_format>0</L24_format>
    <stream_length>-3</stream_length>
    <codecs>flc</codecs>
    <sample_rate>384000</sample_rate>
    <name>Aries</name>
  </device>
  <device>
    <send_coverart>0</send_coverart>
    <accept_nexturi>1</accept_nexturi>
    <mac>bb:bb:a6:65:de:c6</mac>
    <flac_header>1</flac_header>
    <seek_after_pause>1</seek_after_pause>
    <friendly_name>Marantz NA8005</friendly_name>
    <L24_format>0</L24_format>
    <send_metadata>1</send_metadata>
    <udn>uuid:5f9ec1b3-ff59-19bb-8530-000678221602</udn>
    <enabled>1</enabled>
    <mode>thru</mode>
    <codecs>flc,mp3</codecs>
    <stream_length>-3</stream_length>
    <name>Marantz</name>
    <sample_rate>768000</sample_rate>
  </device>
</squeeze2upnp>
____

the whole stuff is running on a multihomed server with 1 Gbit/10 Gbit
the above config is for the 1Gbit interface.

**Comment by mamema** [comment]
<squeeze2upnp>
  <main_log>info</main_log>
  <log_limit>-1</log_limit>
  <output_log>info</output_log>
  <slimproto_log>info</slimproto_log>
  <upnp_log>info</upnp_log>
  <binding>192.168.0.30</binding>
  <common>
    <volume_on_play>1</volume_on_play>
    <codecs>aac,ogg,ops,ogf,flc,alc,wav,aif,pcm,mp3</codecs>
    <raw_audio_format>raw,wav,aif</raw_audio_format>
    <stream_length>-3</stream_length>
    <max_volume>100</max_volume>
    <sample_rate>48000</sample_rate>
    <send_icy>1</send_icy>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>1</send_coverart>
    <flac_header>1</flac_header>
    <seek_after_pause>0</seek_after_pause>
    <streambuf_size>1048576</streambuf_size>
    <roon_mode>0</roon_mode>
    <L24_format>1</L24_format>
    <send_metadata>1</send_metadata>
    <mode>thru</mode>
    <volume_feedback>1</volume_feedback>
    <enabled>1</enabled>
    <next_delay>15</next_delay>
    <auto_play>0</auto_play>
    <remove_timeout>120</remove_timeout>
    <server>?</server>
    <output_size>4194304</output_size>
  </common>
  <decode_log>warn</decode_log>
  <util_log>warn</util_log>
  <stream_log>warn</stream_log>
  <slimmain_log>warn</slimmain_log>
  <device>
    <friendly_name>Aries uPnP </friendly_name>
    <seek_after_pause>1</seek_after_pause>
    <flac_header>1</flac_header>
    <mac>bb:bb:f0:6f:8d:50</mac>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>0</send_coverart>
    <mode>thru</mode>
    <enabled>1</enabled>
    <udn>uuid:lightningRender-bc-34-00-a0-1b-2f</udn>
    <send_metadata>0</send_metadata>
    <L24_format>0</L24_format>
    <stream_length>-3</stream_length>
    <codecs>flc</codecs>
    <sample_rate>384000</sample_rate>
    <name>Aries</name>
  </device>
  <device>
    <send_coverart>0</send_coverart>
    <accept_nexturi>1</accept_nexturi>
    <mac>bb:bb:a6:65:de:c6</mac>
    <flac_header>1</flac_header>
    <seek_after_pause>1</seek_after_pause>
    <friendly_name>Marantz NA8005</friendly_name>
    <L24_format>0</L24_format>
    <send_metadata>1</send_metadata>
    <udn>uuid:5f9ec1b3-ff59-19bb-8530-000678221602</udn>
    <enabled>1</enabled>
    <mode>thru</mode>
    <codecs>flc,mp3</codecs>
    <stream_length>-3</stream_length>
    <name>Marantz</name>
    <sample_rate>768000</sample_rate>
  </device>
</squeeze2upnp>

**Comment by mamema** [comment]
sorry github screw up the XML....can i upload the XML somewhere?

**Comment by philippe44** [comment]
It can't be 192.168.0.x, if this is a literal "x". It must either be your machine's address or a "?" (no"")

**Comment by mamema** [comment]
no, it's just a x, which shows, IP address is there, but it is not your business to know the exact address. :-). Neither ? nor exact machine address are working.....

**Comment by philippe44** [comment]
It's a private non-routable class C address and millions of computers in the world have the same, so nobody cares

**Comment by mamema** [comment]
oh, i'm sorry, no offense on this side of the keyboard. It's just the usual foobar task i'm doing. Sure, i'm happy to provide more information.
As i said. worked before with the last version, before the last update from 12/8/22
`<squeeze2upnp>
  <main_log>info</main_log>
  <log_limit>-1</log_limit>
  <output_log>info</output_log>
  <slimproto_log>info</slimproto_log>
  <upnp_log>info</upnp_log>
  <binding>192.168.0.30</binding>
  <common>
    <volume_on_play>1</volume_on_play>
    <codecs>aac,ogg,ops,ogf,flc,alc,wav,aif,pcm,mp3</codecs>
    <raw_audio_format>raw,wav,aif</raw_audio_format>
    <stream_length>-3</stream_length>
    <max_volume>100</max_volume>
    <sample_rate>48000</sample_rate>
    <send_icy>1</send_icy>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>1</send_coverart>
    <flac_header>1</flac_header>
    <seek_after_pause>0</seek_after_pause>
    <streambuf_size>1048576</streambuf_size>
    <roon_mode>0</roon_mode>
    <L24_format>1</L24_format>
    <send_metadata>1</send_metadata>
    <mode>thru</mode>
    <volume_feedback>1</volume_feedback>
    <enabled>1</enabled>
    <next_delay>15</next_delay>
    <auto_play>0</auto_play>
    <remove_timeout>120</remove_timeout>
    <server>?</server>
    <output_size>4194304</output_size>
  </common>
  <decode_log>warn</decode_log>
  <util_log>warn</util_log>
  <stream_log>warn</stream_log>
  <slimmain_log>warn</slimmain_log>
  <device>
    <friendly_name>Aries uPnP </friendly_name>
    <seek_after_pause>1</seek_after_pause>
    <flac_header>1</flac_header>
    <mac>bb:bb:f0:6f:8d:50</mac>
    <accept_nexturi>1</accept_nexturi>
    <send_coverart>0</send_coverart>
    <mode>thru</mode>
    <enabled>1</enabled>
    <udn>uuid:lightningRender-bc-34-00-a0-1b-2f</udn>
    <send_metadata>0</send_metadata>
    <L24_format>0</L24_format>
    <stream_length>-3</stream_length>
    <codecs>flc</codecs>
    <sample_rate>384000</sample_rate>
    <name>Aries</name>
  </device>
  <device>
    <send_coverart>0</send_coverart>
    <accept_nexturi>1</accept_nexturi>
    <mac>bb:bb:a6:65:de:c6</mac>
    <flac_header>1</flac_header>
    <seek_after_pause>1</seek_after_pause>
    <friendly_name>Marantz NA8005</friendly_name>
    <L24_format>0</L24_format>
    <send_metadata>1</send_metadata>
    <udn>uuid:5f9ec1b3-ff59-19bb-8530-000678221602</udn>
    <enabled>1</enabled>
    <mode>thru</mode>
    <codecs>flc,mp3</codecs>
    <stream_length>-3</stream_length>
    <name>Marantz</name>
    <sample_rate>768000</sample_rate>
  </device>
</squeeze2upnp>
upnpbridge.xml
`

**Comment by philippe44** [comment]
Sorry I'm a bit tense these days. If it is a multi home network, are you sure the nez version is sélecting the right if? That's one thing that has changed for sure. It is usually the cause of the issue on multi homed network. You cal also now specific the name of the IF instead on an address.

**Comment by mamema** [comment]
…oh I’m absolutely NOT sure, that i‘m doing everything right.
So, i‘ll try to explain herr, what i did
- used the statich binary (doing this since 1st day)
- Have three networks on the machine 
    - 192.168.0.0 - LAN 1Gbit 255.255.255.0
    - 192.168.188.0 - Backup LAN 10Gbit
    -  10.1.1.0 - other Net
 
 the LMS Web is and was always on the 1Gbit Network with an appropriate Class C Network address.

- i‘ve tried:
- Recreating XML
- ? As placeholder
- Use LMS interface 
-  Typed in the netadresss of LMS itself
- 

Nothing helped…..

**Comment by philippe44** [comment]
If you know the name of the interface that is connected to the network where the UPnP devices are (like eth0, eth1 ...) then use that in the "network interface" setting

**Comment by mamema** [comment]
That i will try … thanks for the hint. is it important to set the flag ‚use LMS interface‘ then?

**Comment by philippe44** [comment]
No, it should not be set then

**Comment by mamema** [comment]
okay, thank you very much, Philippe, setting the LMS setting to the named interface of my server, solved my connection problems....

**Comment by mamema** [comment]
so today, i guess after auto updating playback stopped on my Marantz NA8005 but still plays on my Aries Mini.
Didn't change a setting.....i'm not sure what i can deliver 
`[15:31:22.828378] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:22.928528] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.000345] process:499 [0xab9f00] strm
[15:31:23.000383] process_strm:240 [0xab9f00] strm command t
[15:31:23.000397] sendSTAT:168 [0xab9f00]: STAT:[STMt] msplayed 0
[15:31:23.000541] process:499 [0xab5a40] strm
[15:31:23.000582] process_strm:240 [0xab5a40] strm command t
[15:31:23.000633] sendSTAT:168 [0xab5a40]: STAT:[STMt] msplayed 0
[15:31:23.003003] UpdateThread:1095 Presence checking
[15:31:23.028679] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.128842] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.228967] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.329137] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.429256] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.529411] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.629579] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.729705] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.829833] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:23.929960] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:24.001502] sendSTAT:168 [0xab9f00]: STAT:[STMt] msplayed 0
[15:31:24.003027] UpdateThread:1095 Presence checking
[15:31:24.030074] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:24.130188] stream_thread:454 [0xab9f00] streambuf read 8 bytes
[15:31:24.230322] stream_thread:454 [0xab9f00] streambuf read 8 bytes
`
