### ISSUE TITLE
strings.txt need to be separated by tabs, not spaces

### ISSUE THREAD

**Issue by michaelherger** [philippe44/LMS-uPnP#69]
https://github.com/philippe44/LMS-uPnP/blob/a9955d32a9426cd47aaf1faf469476dc73e6bace/plugin/strings.txt#L169-L171

**Comment by philippe44** [comment]
Yes I know - just the result of me changing the settings of notepads because many of my other contributions where messy with use of tabs. I of course thought I just did the change for the filetypes that needed spaces but obviously I did not
