### ISSUE TITLE
Plugin settings are no more in LMS interface, so UPNP devices are not availables

### ISSUE THREAD

**Issue by davidanquetin** [philippe44/LMS-uPnP#72]
Since plugin update...

              Same problem here, UPNP plugin is no more in the settings list, even with default theme (so it is not only with material skin)

_Originally posted by @davidanquetin in https://github.com/philippe44/LMS-uPnP/issues/71#issuecomment-1427908124_

**Comment by philippe44** [comment]
How old js you LMS

**Comment by davidanquetin** [comment]
Logitech Media Server Version : 8.0.0 - 1605892077 @ Fri Nov 20 18:28:44 CET 2020

**Comment by philippe44** [comment]
This new version is only compatible with 8.2+

**Comment by davidanquetin** [comment]
ok how can i downgrade to old version ?

**Comment by philippe44** [comment]
I don't know, LMS should not have let you upgrade in the first place
