### ISSUE TITLE
Daphile Flac files above 48kHz

### ISSUE THREAD

**Issue by t0mc4t87** [philippe44/LMS-uPnP#77]
Hi, yesterday, I noticed a problem: when transferring FLAC files with frequencies above 48kHz the music stuttering every few seconds. Below 48kHz there is no problem. I haven't played these songs for a long time so I don't know what caused this problem, but I'm sure they were previously send to amplifier without a problem. The plug-in installed on Daphile transmits sound to the Yamaha receiver (amplifier). Thank you for your reply and help.

**Comment by philippe44** [comment]
I usually don't check issues here, can you please use the LMS forum?
